#!/bin/sh

emux_socket_prefix="/tmp/wemux"
greating="thank you for pairing with me"

server_running(){
  wemux_server_sockets=$wemux_socket_prefix*
  for wemux_server in $wemux_server_sockets; do
    redirect=`tmux -S $wemux_server server-info 2>&1`; server_running=$?
    if [ "$server_running" == 0 ]; then
      return 0
    fi
  done
  return 1
}

if ! server_running; then
  exit 1
fi

trap '' 2 20 24

echo ""

echo $greating

echo ""

while :
do
  read -p  $'how whould you like to connect? [? for help]\n> ' session_type
  case $session_type in
    "?")
      echo
      echo "the way you would like to connect eg. pair mirror"
      echo "better help to come"
      ;;
    "pair")
        wemux pair
      ;;
    "rogue")
      wemux rogue
      ;;
    "mirror")
      wemux mirror
      ;;
    "exit")
      exit
      ;;
    *)
      echo
      echo "thats not an option"
      echo
      ;;
  esac
done
exit
