#!/bin/sh


host_list=(change_this_in_wemux_conf)
socket_prefix="/tmp/wemux"
options="-u"
allow_pair_mode="true"
allow_rogue_mode="true"
default_client_mode="mirror"
allow_kick_user="true"
allow_server_change="false"
default_server_name="wemux"
allow_server_list="true"
allow_user_list="true"
announce_attach="true"
announce_server_change="true"
greating="thank you for pairing with me"

# Load configuration options from /usr/local/etc/wemux.conf
[ -f /usr/local/etc/wemux.conf ] && . /usr/local/etc/wemux.conf


#add a user to a list to keep track of all users on the session
add_user(){
    echo $name >> ~/.users
}

#check if the server is running
server_running(){
  wemux_server_sockets=$socket_prefix*
  for wemux_server in $wemux_server_sockets; do
    redirect=`tmux -S $wemux_server server-info 2>&1`; server_running=$?
    if [ "$server_running" == 0 ]; then
      return 0
    fi
  done
  return 1
}

if ! server_running; then
  exit 1
fi

trap '' 2 20 24

echo ""

echo $greating

echo ""
#get a name from the user that they would like to use during the session 
read -p  "what is your name name/alias? [? for help]
> " name && add_user

echo ""
#if the host alows it ask for the way they want to connect eg. pair mirror rouge
read -p  "how whould you like to connect? [? for help] 
> " session_type

wemux $session_type 
